site_name: Summer & Capoo's Home

theme:
    name: material # 主题名称
    logo: assets/mmc.jpg # logo 图片
    language: zh # 默认语言
    favicon: assets/mmc.jpg # 网站图标
    icon:
      logo: fontawesome/solid/mug-hot
    features:
      - navigation.tabs # 导航栏
      - navigation.expand # 导航栏展开
      - navigation.path   # 导航栏路径
      - navigation.top  # 回到顶部
      # - toc.integrate
    palette: 
        # Palette toggle for light mode
        - scheme: default
          toggle:
            icon: material/brightness-7 
            name: Switch to dark mode
        # Palette toggle for dark mode
        - scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - md_in_html 
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.tabbed:
        alternate_style: true
    - abbr
    - attr_list
    - pymdownx.blocks.caption
    - def_list
    - footnotes
    - toc:
        permalink: true
        toc_depth: 4
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.emoji:
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
        emoji_index: !!python/name:material.extensions.emoji.twemoji
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink:
        normalize_issue_symbols: true
        repo_url_shorthand: true
        user: squidfunk
        repo: mkdocs-material
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.snippets:
        auto_append:
          - includes/mkdocs.md
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
        alternate_style: true
        combine_header_slug: true
        slugify: !!python/object/apply:pymdownx.slugs.slugify
          kwds:
            case: lower
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.critic:
        mode: view
  

        
extra_javascript:
    - javascripts/katex.js
    - https://unpkg.com/katex@0/dist/katex.min.js
    - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.4/katex.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.4/contrib/auto-render.min.js
    - javascripts/mathjax.js
    - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

nav:
    - Homepage: index.md
    - Algèbre:
        - Chapitre 4 Permutations: Algèbre/Permutations.md
    - Analyse:
        - Chapitre 7 Intégration: Analyse/Intégration.md
    - Géométrie:
        - Chapitre 1 Espace Vectoriels: Géométrie/Espace Vectoriels.md
    - Électromagnétisme:
        - Chapitre 1 Analyse vectorielle: Électromagnétisme/Analyse vectorielle.md