site_name: notes
theme:
    name: material
    logo: assets/mmc.jpg
    language: zh
    favicon: assets/mmc.jpg
    features:
      - navigation.tabs
      - navigation.expand
      - navigation.path
      - navigation.top
      # - toc.integrate
    palette: 

        # Palette toggle for light mode
        - scheme: default
          toggle:
            icon: material/brightness-7 
            name: Switch to dark mode

        # Palette toggle for dark mode
        - scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to light mode
nav:
    - algebre:

        - Lec1 置换群: algebre/permutations.md